// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMHoVDJ3pplDNOnQ6MT4H47-StFlvE76I',
    appId: '1:156138335674:web:bbb30832bd61f97573c183',
    messagingSenderId: '156138335674',
    projectId: 'gr11-codestaxh-fall-2025',
    authDomain: 'gr11-codestaxh-fall-2025.firebaseapp.com',
    storageBucket: 'gr11-codestaxh-fall-2025.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChfxjywP4F-tYlzka4W4pEDBgmcSxaEBE',
    appId: '1:156138335674:android:b74e19b65143dad973c183',
    messagingSenderId: '156138335674',
    projectId: 'gr11-codestaxh-fall-2025',
    storageBucket: 'gr11-codestaxh-fall-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKQChSqzAM3lLPIJo_6TfGbRgiRyS-pBI',
    appId: '1:156138335674:ios:df83b5557fb0aa2573c183',
    messagingSenderId: '156138335674',
    projectId: 'gr11-codestaxh-fall-2025',
    storageBucket: 'gr11-codestaxh-fall-2025.firebasestorage.app',
    iosBundleId: 'com.example.codestaxh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKQChSqzAM3lLPIJo_6TfGbRgiRyS-pBI',
    appId: '1:156138335674:ios:df83b5557fb0aa2573c183',
    messagingSenderId: '156138335674',
    projectId: 'gr11-codestaxh-fall-2025',
    storageBucket: 'gr11-codestaxh-fall-2025.firebasestorage.app',
    iosBundleId: 'com.example.codestaxh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMHoVDJ3pplDNOnQ6MT4H47-StFlvE76I',
    appId: '1:156138335674:web:9660cfca5ca95a1c73c183',
    messagingSenderId: '156138335674',
    projectId: 'gr11-codestaxh-fall-2025',
    authDomain: 'gr11-codestaxh-fall-2025.firebaseapp.com',
    storageBucket: 'gr11-codestaxh-fall-2025.firebasestorage.app',
  );
}
