// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:codestaxh/models/snippet.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(SnippetAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(SnippetAdapter());
  }
}
